### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by THHHomas** [bernhardmgruber/bpa#1]
and, What is dependency of the project?

**Comment by bernhardmgruber** [comment]
Thank you for the feedback! I have added small build instructions to the README.md. For Linux the following should be sufficient:
```
git clone https://github.com/bernhardmgruber/bpa.git
mkdir bpa/build
cd bpa/build
cmake ..
make
```
For Windows skip the `make` and open the solution and build in VS.

Be careful that this is a hobby project and not ready for use in production code. It also requires a fairly recent toolchain and libraries. I normally work with VS2019 and I just tried g++ 10.

That should get you started! If you have more troubles, try gooling for build instructions using CMake!
