### ISSUE TITLE
How to run the program

### ISSUE THREAD

**Issue by MinchoU** [bernhardmgruber/bpa#5]
Hello! I'm pretty new to these cmake and make system so I'm having trouble running this algorithm.. After successfully running "make" in build folder, I tried to run executable "tests" by

**g++ -std=c++20 tests**

 but returned error message with 

/usr/bin/ld: tests: _ZTVSt9exception: invalid version 4 (max 0)
/usr/bin/ld: tests: error adding symbols: bad value
collect2: error: ld returned 1 exit status

Can I get some help? Thanks :)

**Comment by bernhardmgruber** [comment]
After building the project with `make`, you can run the test executable with `./tests`. Notice, I also just added a small driver executable so you can call the BPA implementation from the command-line. Just try `./bpa ...`.

**Comment by MinchoU** [comment]
I see. Thanks for your help!
